### ISSUE TITLE
Current To-Do

### ISSUE THREAD

**Issue by Hongyu-He** [Hongyu-He/ece685_project#7]
# Experiments

- [ ] centralized model training and test: 70 epochs, resnext50-32/4d, plot train and val accuracy vs epoch; save best model and test the best model on test set. 
- [ ] tune federated averaging: get compatible results.
- [ ] implement non-iid sampling.
- [ ] Compare centralized model accuracy with federated averaging.
- [ ] Using 1/5 dataset to train centralized model and compare it with federated averaging.
- [ ] Train federated averaging model using non-iid data.
- [ ] implement FedProx to improve performance on non-iid data

# Report

- [ ] see overleaf project
